name: Build and Push Multi-Arch Docker Images

on:
  workflow_dispatch: {}

jobs:
  build-php-8-3:
    name: Build PHP 8.3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push PHP 8.3
        uses: docker/build-push-action@v6
        with:
          context: ./final/8.3
          file: ./final/8.3/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.IMAGE }}:8.3

  build-php-8-4:
    name: Build PHP 8.4
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push PHP 8.4 and latest
        uses: docker/build-push-action@v6
        with:
          context: ./final/8.4
          file: ./final/8.4/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.IMAGE }}:8.4
            ${{ vars.IMAGE }}:latest
